server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mydb
    password: 123456

Logging:
  level:
    com.wms: debug